// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vo "github.com/joshuarp/withdraw-api/internal/domain/vo"
)

// AuthLoginService is an autogenerated mock type for the AuthLoginService type
type AuthLoginService struct {
	mock.Mock
}

type AuthLoginService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthLoginService) EXPECT() *AuthLoginService_Expecter {
	return &AuthLoginService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthLoginService) Login(ctx context.Context, email string, password string) (vo.AuthLogin, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 vo.AuthLogin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (vo.AuthLogin, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) vo.AuthLogin); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(vo.AuthLogin)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthLoginService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthLoginService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthLoginService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *AuthLoginService_Login_Call {
	return &AuthLoginService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *AuthLoginService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *AuthLoginService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthLoginService_Login_Call) Return(_a0 vo.AuthLogin, _a1 error) *AuthLoginService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthLoginService_Login_Call) RunAndReturn(run func(context.Context, string, string) (vo.AuthLogin, error)) *AuthLoginService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthLoginService creates a new instance of AuthLoginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthLoginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthLoginService {
	mock := &AuthLoginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
