// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vo "github.com/joshuarp/withdraw-api/internal/domain/vo"
)

// BalanceWithdrawService is an autogenerated mock type for the BalanceWithdrawService type
type BalanceWithdrawService struct {
	mock.Mock
}

type BalanceWithdrawService_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceWithdrawService) EXPECT() *BalanceWithdrawService_Expecter {
	return &BalanceWithdrawService_Expecter{mock: &_m.Mock}
}

// WithdrawBalance provides a mock function with given fields: ctx, userID, amountMinor, chainID
func (_m *BalanceWithdrawService) WithdrawBalance(ctx context.Context, userID string, amountMinor int64, chainID string) (vo.WalletWithdrawal, error) {
	ret := _m.Called(ctx, userID, amountMinor, chainID)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawBalance")
	}

	var r0 vo.WalletWithdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) (vo.WalletWithdrawal, error)); ok {
		return rf(ctx, userID, amountMinor, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) vo.WalletWithdrawal); ok {
		r0 = rf(ctx, userID, amountMinor, chainID)
	} else {
		r0 = ret.Get(0).(vo.WalletWithdrawal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, string) error); ok {
		r1 = rf(ctx, userID, amountMinor, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceWithdrawService_WithdrawBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawBalance'
type BalanceWithdrawService_WithdrawBalance_Call struct {
	*mock.Call
}

// WithdrawBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - amountMinor int64
//   - chainID string
func (_e *BalanceWithdrawService_Expecter) WithdrawBalance(ctx interface{}, userID interface{}, amountMinor interface{}, chainID interface{}) *BalanceWithdrawService_WithdrawBalance_Call {
	return &BalanceWithdrawService_WithdrawBalance_Call{Call: _e.mock.On("WithdrawBalance", ctx, userID, amountMinor, chainID)}
}

func (_c *BalanceWithdrawService_WithdrawBalance_Call) Run(run func(ctx context.Context, userID string, amountMinor int64, chainID string)) *BalanceWithdrawService_WithdrawBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *BalanceWithdrawService_WithdrawBalance_Call) Return(_a0 vo.WalletWithdrawal, _a1 error) *BalanceWithdrawService_WithdrawBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceWithdrawService_WithdrawBalance_Call) RunAndReturn(run func(context.Context, string, int64, string) (vo.WalletWithdrawal, error)) *BalanceWithdrawService_WithdrawBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceWithdrawService creates a new instance of BalanceWithdrawService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceWithdrawService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceWithdrawService {
	mock := &BalanceWithdrawService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
