// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vo "github.com/joshuarp/withdraw-api/internal/domain/vo"
)

// BalanceInquiryService is an autogenerated mock type for the BalanceInquiryService type
type BalanceInquiryService struct {
	mock.Mock
}

type BalanceInquiryService_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceInquiryService) EXPECT() *BalanceInquiryService_Expecter {
	return &BalanceInquiryService_Expecter{mock: &_m.Mock}
}

// CheckBalance provides a mock function with given fields: ctx, userID
func (_m *BalanceInquiryService) CheckBalance(ctx context.Context, userID string) (vo.BalanceInquiry, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckBalance")
	}

	var r0 vo.BalanceInquiry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (vo.BalanceInquiry, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) vo.BalanceInquiry); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(vo.BalanceInquiry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceInquiryService_CheckBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalance'
type BalanceInquiryService_CheckBalance_Call struct {
	*mock.Call
}

// CheckBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *BalanceInquiryService_Expecter) CheckBalance(ctx interface{}, userID interface{}) *BalanceInquiryService_CheckBalance_Call {
	return &BalanceInquiryService_CheckBalance_Call{Call: _e.mock.On("CheckBalance", ctx, userID)}
}

func (_c *BalanceInquiryService_CheckBalance_Call) Run(run func(ctx context.Context, userID string)) *BalanceInquiryService_CheckBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BalanceInquiryService_CheckBalance_Call) Return(_a0 vo.BalanceInquiry, _a1 error) *BalanceInquiryService_CheckBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceInquiryService_CheckBalance_Call) RunAndReturn(run func(context.Context, string) (vo.BalanceInquiry, error)) *BalanceInquiryService_CheckBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceInquiryService creates a new instance of BalanceInquiryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceInquiryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceInquiryService {
	mock := &BalanceInquiryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
