// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlc "github.com/joshuarp/withdraw-api/internal/shared/sqlc"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// GetWalletBalanceByUserID provides a mock function with given fields: ctx, userID
func (_m *Querier) GetWalletBalanceByUserID(ctx context.Context, userID uuid.UUID) (sqlc.GetWalletBalanceByUserIDRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletBalanceByUserID")
	}

	var r0 sqlc.GetWalletBalanceByUserIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.GetWalletBalanceByUserIDRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.GetWalletBalanceByUserIDRow); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(sqlc.GetWalletBalanceByUserIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetWalletBalanceByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletBalanceByUserID'
type Querier_GetWalletBalanceByUserID_Call struct {
	*mock.Call
}

// GetWalletBalanceByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Querier_Expecter) GetWalletBalanceByUserID(ctx interface{}, userID interface{}) *Querier_GetWalletBalanceByUserID_Call {
	return &Querier_GetWalletBalanceByUserID_Call{Call: _e.mock.On("GetWalletBalanceByUserID", ctx, userID)}
}

func (_c *Querier_GetWalletBalanceByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Querier_GetWalletBalanceByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Querier_GetWalletBalanceByUserID_Call) Return(_a0 sqlc.GetWalletBalanceByUserIDRow, _a1 error) *Querier_GetWalletBalanceByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetWalletBalanceByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (sqlc.GetWalletBalanceByUserIDRow, error)) *Querier_GetWalletBalanceByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// HasWalletByUserID provides a mock function with given fields: ctx, userID
func (_m *Querier) HasWalletByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for HasWalletByUserID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_HasWalletByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasWalletByUserID'
type Querier_HasWalletByUserID_Call struct {
	*mock.Call
}

// HasWalletByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Querier_Expecter) HasWalletByUserID(ctx interface{}, userID interface{}) *Querier_HasWalletByUserID_Call {
	return &Querier_HasWalletByUserID_Call{Call: _e.mock.On("HasWalletByUserID", ctx, userID)}
}

func (_c *Querier_HasWalletByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Querier_HasWalletByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Querier_HasWalletByUserID_Call) Return(_a0 bool, _a1 error) *Querier_HasWalletByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_HasWalletByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *Querier_HasWalletByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertWalletLedger provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertWalletLedger(ctx context.Context, arg sqlc.InsertWalletLedgerParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertWalletLedger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.InsertWalletLedgerParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_InsertWalletLedger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertWalletLedger'
type Querier_InsertWalletLedger_Call struct {
	*mock.Call
}

// InsertWalletLedger is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.InsertWalletLedgerParams
func (_e *Querier_Expecter) InsertWalletLedger(ctx interface{}, arg interface{}) *Querier_InsertWalletLedger_Call {
	return &Querier_InsertWalletLedger_Call{Call: _e.mock.On("InsertWalletLedger", ctx, arg)}
}

func (_c *Querier_InsertWalletLedger_Call) Run(run func(ctx context.Context, arg sqlc.InsertWalletLedgerParams)) *Querier_InsertWalletLedger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.InsertWalletLedgerParams))
	})
	return _c
}

func (_c *Querier_InsertWalletLedger_Call) Return(_a0 error) *Querier_InsertWalletLedger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_InsertWalletLedger_Call) RunAndReturn(run func(context.Context, sqlc.InsertWalletLedgerParams) error) *Querier_InsertWalletLedger_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawWalletBalanceByUserID provides a mock function with given fields: ctx, arg
func (_m *Querier) WithdrawWalletBalanceByUserID(ctx context.Context, arg sqlc.WithdrawWalletBalanceByUserIDParams) (sqlc.WithdrawWalletBalanceByUserIDRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawWalletBalanceByUserID")
	}

	var r0 sqlc.WithdrawWalletBalanceByUserIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.WithdrawWalletBalanceByUserIDParams) (sqlc.WithdrawWalletBalanceByUserIDRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.WithdrawWalletBalanceByUserIDParams) sqlc.WithdrawWalletBalanceByUserIDRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.WithdrawWalletBalanceByUserIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.WithdrawWalletBalanceByUserIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_WithdrawWalletBalanceByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawWalletBalanceByUserID'
type Querier_WithdrawWalletBalanceByUserID_Call struct {
	*mock.Call
}

// WithdrawWalletBalanceByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.WithdrawWalletBalanceByUserIDParams
func (_e *Querier_Expecter) WithdrawWalletBalanceByUserID(ctx interface{}, arg interface{}) *Querier_WithdrawWalletBalanceByUserID_Call {
	return &Querier_WithdrawWalletBalanceByUserID_Call{Call: _e.mock.On("WithdrawWalletBalanceByUserID", ctx, arg)}
}

func (_c *Querier_WithdrawWalletBalanceByUserID_Call) Run(run func(ctx context.Context, arg sqlc.WithdrawWalletBalanceByUserIDParams)) *Querier_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.WithdrawWalletBalanceByUserIDParams))
	})
	return _c
}

func (_c *Querier_WithdrawWalletBalanceByUserID_Call) Return(_a0 sqlc.WithdrawWalletBalanceByUserIDRow, _a1 error) *Querier_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_WithdrawWalletBalanceByUserID_Call) RunAndReturn(run func(context.Context, sqlc.WithdrawWalletBalanceByUserIDParams) (sqlc.WithdrawWalletBalanceByUserIDRow, error)) *Querier_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
