// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	idempotency "github.com/joshuarp/withdraw-api/internal/shared/idempotency"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx, request
func (_m *Store) Acquire(ctx context.Context, request idempotency.Request) (idempotency.Decision, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 idempotency.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.Request) (idempotency.Decision, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.Request) idempotency.Decision); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(idempotency.Decision)
	}

	if rf, ok := ret.Get(1).(func(context.Context, idempotency.Request) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type Store_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - request idempotency.Request
func (_e *Store_Expecter) Acquire(ctx interface{}, request interface{}) *Store_Acquire_Call {
	return &Store_Acquire_Call{Call: _e.mock.On("Acquire", ctx, request)}
}

func (_c *Store_Acquire_Call) Run(run func(ctx context.Context, request idempotency.Request)) *Store_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(idempotency.Request))
	})
	return _c
}

func (_c *Store_Acquire_Call) Return(_a0 idempotency.Decision, _a1 error) *Store_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Acquire_Call) RunAndReturn(run func(context.Context, idempotency.Request) (idempotency.Decision, error)) *Store_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx, request, response
func (_m *Store) Complete(ctx context.Context, request idempotency.Request, response idempotency.StoredResponse) error {
	ret := _m.Called(ctx, request, response)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.Request, idempotency.StoredResponse) error); ok {
		r0 = rf(ctx, request, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type Store_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - request idempotency.Request
//   - response idempotency.StoredResponse
func (_e *Store_Expecter) Complete(ctx interface{}, request interface{}, response interface{}) *Store_Complete_Call {
	return &Store_Complete_Call{Call: _e.mock.On("Complete", ctx, request, response)}
}

func (_c *Store_Complete_Call) Run(run func(ctx context.Context, request idempotency.Request, response idempotency.StoredResponse)) *Store_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(idempotency.Request), args[2].(idempotency.StoredResponse))
	})
	return _c
}

func (_c *Store_Complete_Call) Return(_a0 error) *Store_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Complete_Call) RunAndReturn(run func(context.Context, idempotency.Request, idempotency.StoredResponse) error) *Store_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
