// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ConfigProvider is an autogenerated mock type for the ConfigProvider type
type ConfigProvider struct {
	mock.Mock
}

type ConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigProvider) EXPECT() *ConfigProvider_Expecter {
	return &ConfigProvider_Expecter{mock: &_m.Mock}
}

// AllSettings provides a mock function with no fields
func (_m *ConfigProvider) AllSettings() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllSettings")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// ConfigProvider_AllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSettings'
type ConfigProvider_AllSettings_Call struct {
	*mock.Call
}

// AllSettings is a helper method to define mock.On call
func (_e *ConfigProvider_Expecter) AllSettings() *ConfigProvider_AllSettings_Call {
	return &ConfigProvider_AllSettings_Call{Call: _e.mock.On("AllSettings")}
}

func (_c *ConfigProvider_AllSettings_Call) Run(run func()) *ConfigProvider_AllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigProvider_AllSettings_Call) Return(_a0 map[string]interface{}) *ConfigProvider_AllSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_AllSettings_Call) RunAndReturn(run func() map[string]interface{}) *ConfigProvider_AllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function with given fields: key
func (_m *ConfigProvider) GetBool(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ConfigProvider_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type ConfigProvider_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetBool(key interface{}) *ConfigProvider_GetBool_Call {
	return &ConfigProvider_GetBool_Call{Call: _e.mock.On("GetBool", key)}
}

func (_c *ConfigProvider_GetBool_Call) Run(run func(key string)) *ConfigProvider_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetBool_Call) Return(_a0 bool) *ConfigProvider_GetBool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetBool_Call) RunAndReturn(run func(string) bool) *ConfigProvider_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function with given fields: key
func (_m *ConfigProvider) GetDuration(key string) time.Duration {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// ConfigProvider_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type ConfigProvider_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetDuration(key interface{}) *ConfigProvider_GetDuration_Call {
	return &ConfigProvider_GetDuration_Call{Call: _e.mock.On("GetDuration", key)}
}

func (_c *ConfigProvider_GetDuration_Call) Run(run func(key string)) *ConfigProvider_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetDuration_Call) Return(_a0 time.Duration) *ConfigProvider_GetDuration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetDuration_Call) RunAndReturn(run func(string) time.Duration) *ConfigProvider_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat64 provides a mock function with given fields: key
func (_m *ConfigProvider) GetFloat64(key string) float64 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat64")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// ConfigProvider_GetFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat64'
type ConfigProvider_GetFloat64_Call struct {
	*mock.Call
}

// GetFloat64 is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetFloat64(key interface{}) *ConfigProvider_GetFloat64_Call {
	return &ConfigProvider_GetFloat64_Call{Call: _e.mock.On("GetFloat64", key)}
}

func (_c *ConfigProvider_GetFloat64_Call) Run(run func(key string)) *ConfigProvider_GetFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetFloat64_Call) Return(_a0 float64) *ConfigProvider_GetFloat64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetFloat64_Call) RunAndReturn(run func(string) float64) *ConfigProvider_GetFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function with given fields: key
func (_m *ConfigProvider) GetInt(key string) int {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ConfigProvider_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type ConfigProvider_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetInt(key interface{}) *ConfigProvider_GetInt_Call {
	return &ConfigProvider_GetInt_Call{Call: _e.mock.On("GetInt", key)}
}

func (_c *ConfigProvider_GetInt_Call) Run(run func(key string)) *ConfigProvider_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetInt_Call) Return(_a0 int) *ConfigProvider_GetInt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetInt_Call) RunAndReturn(run func(string) int) *ConfigProvider_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function with given fields: key
func (_m *ConfigProvider) GetString(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ConfigProvider_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type ConfigProvider_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetString(key interface{}) *ConfigProvider_GetString_Call {
	return &ConfigProvider_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *ConfigProvider_GetString_Call) Run(run func(key string)) *ConfigProvider_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetString_Call) Return(_a0 string) *ConfigProvider_GetString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetString_Call) RunAndReturn(run func(string) string) *ConfigProvider_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMap provides a mock function with given fields: key
func (_m *ConfigProvider) GetStringMap(key string) map[string]interface{} {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMap")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// ConfigProvider_GetStringMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMap'
type ConfigProvider_GetStringMap_Call struct {
	*mock.Call
}

// GetStringMap is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetStringMap(key interface{}) *ConfigProvider_GetStringMap_Call {
	return &ConfigProvider_GetStringMap_Call{Call: _e.mock.On("GetStringMap", key)}
}

func (_c *ConfigProvider_GetStringMap_Call) Run(run func(key string)) *ConfigProvider_GetStringMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetStringMap_Call) Return(_a0 map[string]interface{}) *ConfigProvider_GetStringMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetStringMap_Call) RunAndReturn(run func(string) map[string]interface{}) *ConfigProvider_GetStringMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringSlice provides a mock function with given fields: key
func (_m *ConfigProvider) GetStringSlice(key string) []string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringSlice")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ConfigProvider_GetStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringSlice'
type ConfigProvider_GetStringSlice_Call struct {
	*mock.Call
}

// GetStringSlice is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) GetStringSlice(key interface{}) *ConfigProvider_GetStringSlice_Call {
	return &ConfigProvider_GetStringSlice_Call{Call: _e.mock.On("GetStringSlice", key)}
}

func (_c *ConfigProvider_GetStringSlice_Call) Run(run func(key string)) *ConfigProvider_GetStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_GetStringSlice_Call) Return(_a0 []string) *ConfigProvider_GetStringSlice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_GetStringSlice_Call) RunAndReturn(run func(string) []string) *ConfigProvider_GetStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function with given fields: key
func (_m *ConfigProvider) IsSet(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ConfigProvider_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type ConfigProvider_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - key string
func (_e *ConfigProvider_Expecter) IsSet(key interface{}) *ConfigProvider_IsSet_Call {
	return &ConfigProvider_IsSet_Call{Call: _e.mock.On("IsSet", key)}
}

func (_c *ConfigProvider_IsSet_Call) Run(run func(key string)) *ConfigProvider_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigProvider_IsSet_Call) Return(_a0 bool) *ConfigProvider_IsSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_IsSet_Call) RunAndReturn(run func(string) bool) *ConfigProvider_IsSet_Call {
	_c.Call.Return(run)
	return _c
}

// OnChange provides a mock function with given fields: fn
func (_m *ConfigProvider) OnChange(fn func()) {
	_m.Called(fn)
}

// ConfigProvider_OnChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChange'
type ConfigProvider_OnChange_Call struct {
	*mock.Call
}

// OnChange is a helper method to define mock.On call
//   - fn func()
func (_e *ConfigProvider_Expecter) OnChange(fn interface{}) *ConfigProvider_OnChange_Call {
	return &ConfigProvider_OnChange_Call{Call: _e.mock.On("OnChange", fn)}
}

func (_c *ConfigProvider_OnChange_Call) Run(run func(fn func())) *ConfigProvider_OnChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *ConfigProvider_OnChange_Call) Return() *ConfigProvider_OnChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConfigProvider_OnChange_Call) RunAndReturn(run func(func())) *ConfigProvider_OnChange_Call {
	_c.Run(run)
	return _c
}

// Source provides a mock function with no fields
func (_m *ConfigProvider) Source() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Source")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ConfigProvider_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type ConfigProvider_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *ConfigProvider_Expecter) Source() *ConfigProvider_Source_Call {
	return &ConfigProvider_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *ConfigProvider_Source_Call) Run(run func()) *ConfigProvider_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigProvider_Source_Call) Return(_a0 string) *ConfigProvider_Source_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigProvider_Source_Call) RunAndReturn(run func() string) *ConfigProvider_Source_Call {
	_c.Call.Return(run)
	return _c
}

// StopWatching provides a mock function with no fields
func (_m *ConfigProvider) StopWatching() {
	_m.Called()
}

// ConfigProvider_StopWatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWatching'
type ConfigProvider_StopWatching_Call struct {
	*mock.Call
}

// StopWatching is a helper method to define mock.On call
func (_e *ConfigProvider_Expecter) StopWatching() *ConfigProvider_StopWatching_Call {
	return &ConfigProvider_StopWatching_Call{Call: _e.mock.On("StopWatching")}
}

func (_c *ConfigProvider_StopWatching_Call) Run(run func()) *ConfigProvider_StopWatching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigProvider_StopWatching_Call) Return() *ConfigProvider_StopWatching_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConfigProvider_StopWatching_Call) RunAndReturn(run func()) *ConfigProvider_StopWatching_Call {
	_c.Run(run)
	return _c
}

// WatchChanges provides a mock function with no fields
func (_m *ConfigProvider) WatchChanges() {
	_m.Called()
}

// ConfigProvider_WatchChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchChanges'
type ConfigProvider_WatchChanges_Call struct {
	*mock.Call
}

// WatchChanges is a helper method to define mock.On call
func (_e *ConfigProvider_Expecter) WatchChanges() *ConfigProvider_WatchChanges_Call {
	return &ConfigProvider_WatchChanges_Call{Call: _e.mock.On("WatchChanges")}
}

func (_c *ConfigProvider_WatchChanges_Call) Run(run func()) *ConfigProvider_WatchChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigProvider_WatchChanges_Call) Return() *ConfigProvider_WatchChanges_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConfigProvider_WatchChanges_Call) RunAndReturn(run func()) *ConfigProvider_WatchChanges_Call {
	_c.Run(run)
	return _c
}

// NewConfigProvider creates a new instance of ConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigProvider {
	mock := &ConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
