// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/joshuarp/withdraw-api/internal/shared/jwt"
	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function with given fields: ctx, claims
func (_m *TokenManager) Sign(ctx context.Context, claims jwt.Claims) (string, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) (string, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) string); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, jwt.Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type TokenManager_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - claims jwt.Claims
func (_e *TokenManager_Expecter) Sign(ctx interface{}, claims interface{}) *TokenManager_Sign_Call {
	return &TokenManager_Sign_Call{Call: _e.mock.On("Sign", ctx, claims)}
}

func (_c *TokenManager_Sign_Call) Run(run func(ctx context.Context, claims jwt.Claims)) *TokenManager_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jwt.Claims))
	})
	return _c
}

func (_c *TokenManager_Sign_Call) Return(_a0 string, _a1 error) *TokenManager_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_Sign_Call) RunAndReturn(run func(context.Context, jwt.Claims) (string, error)) *TokenManager_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, tokenString
func (_m *TokenManager) Verify(ctx context.Context, tokenString string) (*jwt.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *jwt.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenManager_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *TokenManager_Expecter) Verify(ctx interface{}, tokenString interface{}) *TokenManager_Verify_Call {
	return &TokenManager_Verify_Call{Call: _e.mock.On("Verify", ctx, tokenString)}
}

func (_c *TokenManager_Verify_Call) Run(run func(ctx context.Context, tokenString string)) *TokenManager_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenManager_Verify_Call) Return(_a0 *jwt.Claims, _a1 error) *TokenManager_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_Verify_Call) RunAndReturn(run func(context.Context, string) (*jwt.Claims, error)) *TokenManager_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
