// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/joshuarp/withdraw-api/internal/shared/jwt"
	mock "github.com/stretchr/testify/mock"
)

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

type Verifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Verifier) EXPECT() *Verifier_Expecter {
	return &Verifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, tokenString
func (_m *Verifier) Verify(ctx context.Context, tokenString string) (*jwt.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *jwt.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Verifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *Verifier_Expecter) Verify(ctx interface{}, tokenString interface{}) *Verifier_Verify_Call {
	return &Verifier_Verify_Call{Call: _e.mock.On("Verify", ctx, tokenString)}
}

func (_c *Verifier_Verify_Call) Run(run func(ctx context.Context, tokenString string)) *Verifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Verifier_Verify_Call) Return(_a0 *jwt.Claims, _a1 error) *Verifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Verifier_Verify_Call) RunAndReturn(run func(context.Context, string) (*jwt.Claims, error)) *Verifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerifier creates a new instance of Verifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Verifier {
	mock := &Verifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
