// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/joshuarp/withdraw-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthLoginRepository is an autogenerated mock type for the AuthLoginRepository type
type AuthLoginRepository struct {
	mock.Mock
}

type AuthLoginRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthLoginRepository) EXPECT() *AuthLoginRepository_Expecter {
	return &AuthLoginRepository_Expecter{mock: &_m.Mock}
}

// GetUserAuthByEmail provides a mock function with given fields: ctx, email
func (_m *AuthLoginRepository) GetUserAuthByEmail(ctx context.Context, email string) (domain.UserAuth, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAuthByEmail")
	}

	var r0 domain.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.UserAuth, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UserAuth); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.UserAuth)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthLoginRepository_GetUserAuthByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAuthByEmail'
type AuthLoginRepository_GetUserAuthByEmail_Call struct {
	*mock.Call
}

// GetUserAuthByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthLoginRepository_Expecter) GetUserAuthByEmail(ctx interface{}, email interface{}) *AuthLoginRepository_GetUserAuthByEmail_Call {
	return &AuthLoginRepository_GetUserAuthByEmail_Call{Call: _e.mock.On("GetUserAuthByEmail", ctx, email)}
}

func (_c *AuthLoginRepository_GetUserAuthByEmail_Call) Run(run func(ctx context.Context, email string)) *AuthLoginRepository_GetUserAuthByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthLoginRepository_GetUserAuthByEmail_Call) Return(_a0 domain.UserAuth, _a1 error) *AuthLoginRepository_GetUserAuthByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthLoginRepository_GetUserAuthByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.UserAuth, error)) *AuthLoginRepository_GetUserAuthByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthLoginRepository creates a new instance of AuthLoginRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthLoginRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthLoginRepository {
	mock := &AuthLoginRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
