// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/joshuarp/withdraw-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BalanceWithdrawRepository is an autogenerated mock type for the BalanceWithdrawRepository type
type BalanceWithdrawRepository struct {
	mock.Mock
}

type BalanceWithdrawRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceWithdrawRepository) EXPECT() *BalanceWithdrawRepository_Expecter {
	return &BalanceWithdrawRepository_Expecter{mock: &_m.Mock}
}

// WithdrawWalletBalanceByUserID provides a mock function with given fields: ctx, userID, amountMinor, chainID
func (_m *BalanceWithdrawRepository) WithdrawWalletBalanceByUserID(ctx context.Context, userID string, amountMinor int64, chainID string) (domain.WalletBalance, error) {
	ret := _m.Called(ctx, userID, amountMinor, chainID)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawWalletBalanceByUserID")
	}

	var r0 domain.WalletBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) (domain.WalletBalance, error)); ok {
		return rf(ctx, userID, amountMinor, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) domain.WalletBalance); ok {
		r0 = rf(ctx, userID, amountMinor, chainID)
	} else {
		r0 = ret.Get(0).(domain.WalletBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, string) error); ok {
		r1 = rf(ctx, userID, amountMinor, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawWalletBalanceByUserID'
type BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call struct {
	*mock.Call
}

// WithdrawWalletBalanceByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - amountMinor int64
//   - chainID string
func (_e *BalanceWithdrawRepository_Expecter) WithdrawWalletBalanceByUserID(ctx interface{}, userID interface{}, amountMinor interface{}, chainID interface{}) *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call {
	return &BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call{Call: _e.mock.On("WithdrawWalletBalanceByUserID", ctx, userID, amountMinor, chainID)}
}

func (_c *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call) Run(run func(ctx context.Context, userID string, amountMinor int64, chainID string)) *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call) Return(_a0 domain.WalletBalance, _a1 error) *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call) RunAndReturn(run func(context.Context, string, int64, string) (domain.WalletBalance, error)) *BalanceWithdrawRepository_WithdrawWalletBalanceByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceWithdrawRepository creates a new instance of BalanceWithdrawRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceWithdrawRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceWithdrawRepository {
	mock := &BalanceWithdrawRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
