// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/joshuarp/withdraw-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BalanceInquiryRepository is an autogenerated mock type for the BalanceInquiryRepository type
type BalanceInquiryRepository struct {
	mock.Mock
}

type BalanceInquiryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceInquiryRepository) EXPECT() *BalanceInquiryRepository_Expecter {
	return &BalanceInquiryRepository_Expecter{mock: &_m.Mock}
}

// GetWalletBalanceByUserID provides a mock function with given fields: ctx, userID
func (_m *BalanceInquiryRepository) GetWalletBalanceByUserID(ctx context.Context, userID string) (domain.WalletBalance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletBalanceByUserID")
	}

	var r0 domain.WalletBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.WalletBalance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.WalletBalance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.WalletBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceInquiryRepository_GetWalletBalanceByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletBalanceByUserID'
type BalanceInquiryRepository_GetWalletBalanceByUserID_Call struct {
	*mock.Call
}

// GetWalletBalanceByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *BalanceInquiryRepository_Expecter) GetWalletBalanceByUserID(ctx interface{}, userID interface{}) *BalanceInquiryRepository_GetWalletBalanceByUserID_Call {
	return &BalanceInquiryRepository_GetWalletBalanceByUserID_Call{Call: _e.mock.On("GetWalletBalanceByUserID", ctx, userID)}
}

func (_c *BalanceInquiryRepository_GetWalletBalanceByUserID_Call) Run(run func(ctx context.Context, userID string)) *BalanceInquiryRepository_GetWalletBalanceByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BalanceInquiryRepository_GetWalletBalanceByUserID_Call) Return(_a0 domain.WalletBalance, _a1 error) *BalanceInquiryRepository_GetWalletBalanceByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceInquiryRepository_GetWalletBalanceByUserID_Call) RunAndReturn(run func(context.Context, string) (domain.WalletBalance, error)) *BalanceInquiryRepository_GetWalletBalanceByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceInquiryRepository creates a new instance of BalanceInquiryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceInquiryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceInquiryRepository {
	mock := &BalanceInquiryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
