// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inquiry.check.balance.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getWalletBalanceByUserID = `-- name: GetWalletBalanceByUserID :one
SELECT
    w.user_id::text AS user_id,
    w.balance_minor,
    w.currency,
    w.updated_at
FROM wallets AS w
WHERE w.user_id = $1::uuid
LIMIT 1
`

type GetWalletBalanceByUserIDRow struct {
	UserID       string    `json:"user_id"`
	BalanceMinor int64     `json:"balance_minor"`
	Currency     string    `json:"currency"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetWalletBalanceByUserID(ctx context.Context, userID uuid.UUID) (GetWalletBalanceByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalanceByUserID, userID)
	var i GetWalletBalanceByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.BalanceMinor,
		&i.Currency,
		&i.UpdatedAt,
	)
	return i, err
}
