// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inquiry.withdraw.balance.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const hasWalletByUserID = `-- name: HasWalletByUserID :one
SELECT EXISTS (
    SELECT 1
    FROM wallets
    WHERE user_id = $1::uuid
)
`

func (q *Queries) HasWalletByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasWalletByUserID, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWalletLedger = `-- name: InsertWalletLedger :exec
INSERT INTO wallet_ledger (
    wallet_id,
    entry_type,
    amount_minor,
    balance_after_minor,
    reference_id,
    chain_id,
    created_at
)
VALUES (
    $1::uuid,
    $2,
    $3::bigint,
    $4::bigint,
    $5,
    $6,
    now()
)
`

type InsertWalletLedgerParams struct {
	WalletID          uuid.UUID      `json:"wallet_id"`
	EntryType         string         `json:"entry_type"`
	AmountMinor       int64          `json:"amount_minor"`
	BalanceAfterMinor int64          `json:"balance_after_minor"`
	ReferenceID       sql.NullString `json:"reference_id"`
	ChainID           sql.NullString `json:"chain_id"`
}

func (q *Queries) InsertWalletLedger(ctx context.Context, arg InsertWalletLedgerParams) error {
	_, err := q.db.ExecContext(ctx, insertWalletLedger,
		arg.WalletID,
		arg.EntryType,
		arg.AmountMinor,
		arg.BalanceAfterMinor,
		arg.ReferenceID,
		arg.ChainID,
	)
	return err
}

const withdrawWalletBalanceByUserID = `-- name: WithdrawWalletBalanceByUserID :one
UPDATE wallets
SET
    balance_minor = balance_minor - $1::bigint,
    version = version + 1,
    updated_at = now()
WHERE user_id = $2::uuid
  AND balance_minor >= $1::bigint
RETURNING
    id AS wallet_id,
    user_id::text AS user_id,
    balance_minor,
    currency,
    updated_at
`

type WithdrawWalletBalanceByUserIDParams struct {
	AmountMinor int64     `json:"amount_minor"`
	UserID      uuid.UUID `json:"user_id"`
}

type WithdrawWalletBalanceByUserIDRow struct {
	WalletID     uuid.UUID `json:"wallet_id"`
	UserID       string    `json:"user_id"`
	BalanceMinor int64     `json:"balance_minor"`
	Currency     string    `json:"currency"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) WithdrawWalletBalanceByUserID(ctx context.Context, arg WithdrawWalletBalanceByUserIDParams) (WithdrawWalletBalanceByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, withdrawWalletBalanceByUserID, arg.AmountMinor, arg.UserID)
	var i WithdrawWalletBalanceByUserIDRow
	err := row.Scan(
		&i.WalletID,
		&i.UserID,
		&i.BalanceMinor,
		&i.Currency,
		&i.UpdatedAt,
	)
	return i, err
}
