// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Wallet struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	BalanceMinor int64     `json:"balance_minor"`
	Currency     string    `json:"currency"`
	Version      int64     `json:"version"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type WalletLedger struct {
	ID                uuid.UUID      `json:"id"`
	WalletID          uuid.UUID      `json:"wallet_id"`
	EntryType         string         `json:"entry_type"`
	AmountMinor       int64          `json:"amount_minor"`
	BalanceAfterMinor int64          `json:"balance_after_minor"`
	ReferenceID       sql.NullString `json:"reference_id"`
	ChainID           sql.NullString `json:"chain_id"`
	CreatedAt         time.Time      `json:"created_at"`
}
