// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetWalletBalanceByUserID(ctx context.Context, userID uuid.UUID) (GetWalletBalanceByUserIDRow, error)
	HasWalletByUserID(ctx context.Context, userID uuid.UUID) (bool, error)
	InsertWalletLedger(ctx context.Context, arg InsertWalletLedgerParams) error
	WithdrawWalletBalanceByUserID(ctx context.Context, arg WithdrawWalletBalanceByUserIDParams) (WithdrawWalletBalanceByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
