// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UIDGenerator is an autogenerated mock type for the UIDGenerator type
type UIDGenerator struct {
	mock.Mock
}

type UIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *UIDGenerator) EXPECT() *UIDGenerator_Expecter {
	return &UIDGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx
func (_m *UIDGenerator) Generate(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UIDGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type UIDGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UIDGenerator_Expecter) Generate(ctx interface{}) *UIDGenerator_Generate_Call {
	return &UIDGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx)}
}

func (_c *UIDGenerator_Generate_Call) Run(run func(ctx context.Context)) *UIDGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UIDGenerator_Generate_Call) Return(_a0 string, _a1 error) *UIDGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UIDGenerator_Generate_Call) RunAndReturn(run func(context.Context) (string, error)) *UIDGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewUIDGenerator creates a new instance of UIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UIDGenerator {
	mock := &UIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
